### PR TITLE
Made resource headings collapsible

### PR DESCRIPTION
**Pull request by EricJB77**
Referencing issue #26

### CODE REVIEW

**Comment by EricJB77** [comment]
Hopefully I did it correctly.  I made the change based on markdown formatting.  Should I have done it for Jekyll instead?

**Comment by ghost** [comment]
> 
> 
> Hopefully I did it correctly. I made the change based on markdown formatting. Should I have done it for Jekyll instead?

I think markdown is best, so sounds good.

**Comment by shaneSheridan** [comment]
Hi @EricJB77,

The bullet points of resources are not being rendered correctly, it just displays the actual markdown, see image below.
It should be formatted as bullet points.
 
image

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @EricJB77,

The bullet points of resources are not being rendered correctly, it just displays the actual markdown, see image below.

It should be formatted as bullet points.

image

**Comment by EricJB77** [comment]
This is my first time working with Ruby/Jekyll and Markdown so this is all new to me.  Sorry, I should have tested this locally (as I only tested in my remote repo and it looked like it worked (since it was only showing me the markdown code on GitHub, not the finished website).  I checked it on my local copy and I see it's not rendering the code, like you said.

Apparently, the collapsible markdown code that worked on GitHub, doesn't render to HTML, so I [got it to work](https://stackoverflow.com/questions/52944720/content-of-collapsible-sections-detailssummary-renders-markdown-in-gith#comment92827128_52944720) by adding **gem "jekyll-commonmark-ghpages** to  **gemfile** which worked in converting the markdown to HTML but then the "{:target="_blank"} would still show up on the website:

image

After [some research](https://stackoverflow.com/questions/41915571/open-link-in-new-tab-with-github-markdown-using-target-blank) it looks like markdown doesn't support that specific code either (markdown is fun!  :p) unless you install "kramdown" for markdown.  I don't want to add more dependencies to the site so I tried changing some of the links to good 'ol HTML, which works fine in removing the {:target="_blank"} code (see HTML below):

image

I know we wanted to keep things markdown-based, so, my question is, should I go ahead and change the rest of the links on the resource page to HTML, I'd have to do that manually of course, or should we keep them as (is) markdown and find another solution?  Keep in mind, I wouldn't be changing the markdown file to html, I would just be adding embedded html to the markdown file.

Sorry, it's a little long-winded but I wanted to "show my work".  lol  References are in the hyperlinks

**Comment by ghost** [comment]
Hey @EricJB77,
I'm ok with hacking the links with HTML to make them work, let's see how that works.

**Pull request closed without merging**
