### PR TITLE
Favicon

### PR DESCRIPTION
**Pull request by Andy-TE**
noticed the Favicon for the site wasn't appearing.

-Added Assets Folder
-Added favicon.ico to assets folder Source :- (https://codementoring.co/)

Followed guide on adding favicon
- added _includes folder
- added head.html

### CODE REVIEW

**Comment by ghost** [comment]
I'll come back to this one later @Andy-TE, focusing on getting people through the first task at the moment.

**Comment by edgul** [comment]
I can't see favicon when i run locally. Is this issue only for me?

**Comment by Andy-TE** [comment]
Ohh maybe I did this change wrong then?

I don't get them on the code-mentoring.github.io site.

But after I made these change I do get them on local host

image

**Comment by edgul** [comment]
Nvm, it works. I was looking in the wrong spot. Icon appears in the tab, not the url bar. :facepalm:

**Pull request merged**
